{% set name = "openpkflow" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e611165358b7913f9455c0a8a3ded323be870763f2d2a9fa5d438c4055c7bfa5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - numpy >=1.24
    - pandas >=2.0
    - scipy >=1.10
    - matplotlib-base >=3.7
    - pydantic >=2.0
    - typer >=0.12
    - jinja2 >=3.1

test:
  imports:
    - openpkflow
    - openpkflow.nca
    - openpkflow.dissolution
    - openpkflow.sim
    - openpkflow.be
    - openpkflow.ivivc
    - openpkflow.report
    - openpkflow.validation
  commands:
    - pip check
    - openpkflow version
  requires:
    - pip

about:
  home: https://github.com/priyamthakar/openpkflow
  license: MIT
  license_file: LICENSE
  summary: >-
    A transparent, reproducible, open-source Python workflow for dissolution,
    NCA, PK/PD simulation, and pharmacometric reporting.
  doc_url: https://priyamthakar.github.io/openpkflow/
  dev_url: https://github.com/priyamthakar/openpkflow/

extra:
  recipe-maintainers:
    - priyamthakar
