"""Dissolution model fitting cross-validation: base R lm/optim vs openpkflow.

Independent R implementation cross-validation run:
  R script: scripts/dissolution_models_crossval.R
  Strategy: algebraic identity on noise-free synthetic profiles.
  Both R (lm/optim) and openpkflow (scipy.optimize.curve_fit) minimize SSE
  for the same model formula on the same noise-free data; the global minimum
  is at the true parameters (SSE = 0), so both should recover them exactly.

Models validated:
  Zero-order:       Q(t) = k0 * t
  First-order:      Q(t) = 100 * (1 - exp(-k1 * t))
  Higuchi:          Q(t) = kH * sqrt(t)
  Korsmeyer-Peppas: Q(t) = k * t^n
  Weibull:          Q(t) = 100 * (1 - exp(-(t/beta)^alpha))

Tolerance: 1e-4 relative for all parameters (optimizer convergence).
For linear models (zero-order, Higuchi), R lm() recovers exact OLS solution
and openpkflow curve_fit should match to < 1e-6 relative.

References:
  Costa P, Lobo JMS (2001). Eur J Pharm Sci, 13(2):123-133.
    DOI: 10.1016/S0928-0987(01)00095-1
  FDA Guidance: Dissolution Testing of Immediate Release Solid Oral Dosage
    Forms (1997), CDER.
"""

from __future__ import annotations

import pytest

from openpkflow.dissolution.models import fit_dissolution_models

# ---------------------------------------------------------------------------
# R reference values
#
# Generated by: Rscript scripts/dissolution_models_crossval.R
# Linear models: R lm() (exact OLS); Nonlinear: R optim() Brent/Nelder-Mead
# ---------------------------------------------------------------------------

_TIMEPOINTS = [5, 10, 15, 20, 30, 45, 60, 90, 120]

_MODEL_REFERENCE: dict[str, dict[str, object]] = {
    "zero_order": {
        "true_k0": 0.8000,
        "ref_k0": 0.8000000000,
        "Q": [
            4.0000000000,
            8.0000000000,
            12.0000000000,
            16.0000000000,
            24.0000000000,
            36.0000000000,
            48.0000000000,
            72.0000000000,
            96.0000000000,
        ],
    },
    "first_order": {
        "true_k1": 0.0500,
        "ref_k1": 0.0499999998,
        "Q": [
            22.1199216929,
            39.3469340287,
            52.7633447259,
            63.2120558829,
            77.6869839852,
            89.4600775438,
            95.0212931632,
            98.8891003462,
            99.7521247823,
        ],
    },
    "higuchi": {
        "true_kH": 8.5000,
        "ref_kH": 8.5000000000,
        "Q": [
            19.0065778087,
            26.8793601114,
            32.9203584428,
            38.0131556175,
            46.5564173879,
            57.0197334262,
            65.8407168855,
            80.6380803343,
            93.1128347759,
        ],
    },
    "korsmeyer_peppas": {
        "true_k": 3.0000,
        "true_n": 0.6500,
        "ref_k": 3.0000000000,
        "ref_n": 0.6500000000,
        "Q": [
            8.5398797914,
            13.4005077645,
            17.4413691095,
            21.0276505916,
            27.3684416977,
            35.6212691332,
            42.9456882805,
            55.8957626176,
            67.3890081962,
        ],
    },
    "weibull": {
        "true_alpha": 1.5000,
        "true_beta": 30.0000,
        "ref_alpha": 1.4999999839,
        "ref_beta": 30.0000005039,
        "Q": [
            6.5778186951,
            17.5064510071,
            29.7811498673,
            41.9770204025,
            63.2120558829,
            84.0724091510,
            94.0894253438,
            99.4462169286,
            99.9664537372,
        ],
    },
}

_TOL_NL = 1e-4  # tolerance for nonlinear optimizer (Weibull, KP)
_TOL_LM = 1e-6  # tolerance for linear fits (zero-order, Higuchi)


def _fit(model_name: str, Q: list[float]):
    import warnings

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        result = fit_dissolution_models(_TIMEPOINTS, Q, "test", models=[model_name])
    fits = {f.model_name: f for f in result.fits}
    return fits[model_name]


class TestDissolutionModelFittingCrossValidation:
    """Verify openpkflow dissolution model fitting recovers true parameters.

    R lm/optim independently fits the same models on the same noise-free data.
    On noise-free data generated from a model, both optimizers must converge to
    the true parameters (global SSE minimum = 0).

    Costa P, Lobo JMS (2001). Eur J Pharm Sci, 13(2):123-133.
    DOI: 10.1016/S0928-0987(01)00095-1
    """

    # --- Zero-order ---

    def test_zero_order_converges(self) -> None:
        ref = _MODEL_REFERENCE["zero_order"]
        fit = _fit("zero_order", ref["Q"])
        assert fit.converged, "Zero-order model did not converge"

    def test_zero_order_k0_matches_true(self) -> None:
        ref = _MODEL_REFERENCE["zero_order"]
        fit = _fit("zero_order", ref["Q"])
        assert fit.converged
        assert fit.params["k0"] == pytest.approx(ref["true_k0"], rel=_TOL_LM), (
            f"k0={fit.params['k0']:.8f} vs true={ref['true_k0']:.4f}"
        )

    def test_zero_order_k0_matches_r_lm(self) -> None:
        ref = _MODEL_REFERENCE["zero_order"]
        fit = _fit("zero_order", ref["Q"])
        assert fit.converged
        assert fit.params["k0"] == pytest.approx(ref["ref_k0"], rel=_TOL_LM)

    def test_zero_order_r_squared_near_one(self) -> None:
        ref = _MODEL_REFERENCE["zero_order"]
        fit = _fit("zero_order", ref["Q"])
        assert fit.r_squared == pytest.approx(1.0, abs=1e-6)

    # --- First-order ---

    def test_first_order_converges(self) -> None:
        ref = _MODEL_REFERENCE["first_order"]
        fit = _fit("first_order", ref["Q"])
        assert fit.converged

    def test_first_order_k1_matches_true(self) -> None:
        ref = _MODEL_REFERENCE["first_order"]
        fit = _fit("first_order", ref["Q"])
        assert fit.converged
        assert fit.params["k1"] == pytest.approx(ref["true_k1"], rel=_TOL_NL), (
            f"k1={fit.params['k1']:.8f} vs true={ref['true_k1']:.4f}"
        )

    def test_first_order_k1_matches_r_optim(self) -> None:
        ref = _MODEL_REFERENCE["first_order"]
        fit = _fit("first_order", ref["Q"])
        assert fit.converged
        assert fit.params["k1"] == pytest.approx(ref["ref_k1"], rel=_TOL_NL)

    def test_first_order_r_squared_near_one(self) -> None:
        ref = _MODEL_REFERENCE["first_order"]
        fit = _fit("first_order", ref["Q"])
        assert fit.r_squared == pytest.approx(1.0, abs=1e-6)

    # --- Higuchi ---

    def test_higuchi_converges(self) -> None:
        ref = _MODEL_REFERENCE["higuchi"]
        fit = _fit("higuchi", ref["Q"])
        assert fit.converged

    def test_higuchi_kH_matches_true(self) -> None:
        ref = _MODEL_REFERENCE["higuchi"]
        fit = _fit("higuchi", ref["Q"])
        assert fit.converged
        assert fit.params["kH"] == pytest.approx(ref["true_kH"], rel=_TOL_LM), (
            f"kH={fit.params['kH']:.8f} vs true={ref['true_kH']:.4f}"
        )

    def test_higuchi_kH_matches_r_lm(self) -> None:
        ref = _MODEL_REFERENCE["higuchi"]
        fit = _fit("higuchi", ref["Q"])
        assert fit.params["kH"] == pytest.approx(ref["ref_kH"], rel=_TOL_LM)

    def test_higuchi_r_squared_near_one(self) -> None:
        ref = _MODEL_REFERENCE["higuchi"]
        fit = _fit("higuchi", ref["Q"])
        assert fit.r_squared == pytest.approx(1.0, abs=1e-6)

    # --- Korsmeyer-Peppas ---

    def test_kp_converges(self) -> None:
        ref = _MODEL_REFERENCE["korsmeyer_peppas"]
        fit = _fit("korsmeyer_peppas", ref["Q"])
        assert fit.converged

    def test_kp_k_matches_true(self) -> None:
        ref = _MODEL_REFERENCE["korsmeyer_peppas"]
        fit = _fit("korsmeyer_peppas", ref["Q"])
        assert fit.converged
        assert fit.params["k"] == pytest.approx(ref["true_k"], rel=_TOL_NL), (
            f"k={fit.params['k']:.8f} vs true={ref['true_k']:.4f}"
        )

    def test_kp_n_matches_true(self) -> None:
        ref = _MODEL_REFERENCE["korsmeyer_peppas"]
        fit = _fit("korsmeyer_peppas", ref["Q"])
        assert fit.converged
        assert fit.params["n"] == pytest.approx(ref["true_n"], rel=_TOL_NL), (
            f"n={fit.params['n']:.8f} vs true={ref['true_n']:.4f}"
        )

    def test_kp_k_matches_r_loglin(self) -> None:
        ref = _MODEL_REFERENCE["korsmeyer_peppas"]
        fit = _fit("korsmeyer_peppas", ref["Q"])
        assert fit.params["k"] == pytest.approx(ref["ref_k"], rel=_TOL_NL)

    def test_kp_n_matches_r_loglin(self) -> None:
        ref = _MODEL_REFERENCE["korsmeyer_peppas"]
        fit = _fit("korsmeyer_peppas", ref["Q"])
        assert fit.params["n"] == pytest.approx(ref["ref_n"], rel=_TOL_NL)

    # --- Weibull ---

    def test_weibull_converges(self) -> None:
        ref = _MODEL_REFERENCE["weibull"]
        fit = _fit("weibull", ref["Q"])
        assert fit.converged

    def test_weibull_alpha_matches_true(self) -> None:
        ref = _MODEL_REFERENCE["weibull"]
        fit = _fit("weibull", ref["Q"])
        assert fit.converged
        assert fit.params["alpha"] == pytest.approx(ref["true_alpha"], rel=_TOL_NL), (
            f"alpha={fit.params['alpha']:.8f} vs true={ref['true_alpha']:.4f}"
        )

    def test_weibull_beta_matches_true(self) -> None:
        ref = _MODEL_REFERENCE["weibull"]
        fit = _fit("weibull", ref["Q"])
        assert fit.converged
        assert fit.params["beta"] == pytest.approx(ref["true_beta"], rel=_TOL_NL), (
            f"beta={fit.params['beta']:.8f} vs true={ref['true_beta']:.4f}"
        )

    def test_weibull_alpha_matches_r_optim(self) -> None:
        ref = _MODEL_REFERENCE["weibull"]
        fit = _fit("weibull", ref["Q"])
        assert fit.params["alpha"] == pytest.approx(ref["ref_alpha"], rel=_TOL_NL)

    def test_weibull_beta_matches_r_optim(self) -> None:
        ref = _MODEL_REFERENCE["weibull"]
        fit = _fit("weibull", ref["Q"])
        assert fit.params["beta"] == pytest.approx(ref["ref_beta"], rel=_TOL_NL)

    # --- Model selection sanity ---

    def test_weibull_ranks_first_on_weibull_data(self) -> None:
        """AICc-based model selection: Weibull is best on Weibull-generated data.

        Costa P, Lobo JMS (2001). DOI: 10.1016/S0928-0987(01)00095-1
        """
        import warnings

        ref = _MODEL_REFERENCE["weibull"]
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            results = fit_dissolution_models(_TIMEPOINTS, ref["Q"], "test")
        assert results.best is not None
        assert results.best.model_name == "weibull", (
            f"Expected weibull to rank first, got {results.best.model_name}"
        )

    def test_all_five_models_converge_on_weibull_data(self) -> None:
        import warnings

        ref = _MODEL_REFERENCE["weibull"]
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            results = fit_dissolution_models(_TIMEPOINTS, ref["Q"], "test")
        converged = {f.model_name: f.converged for f in results.fits}
        assert all(converged.values()), f"Some models failed to converge: {converged}"
