"""BE validation: PowerTOST cross-validation of power and sample size.

PowerTOST cross-validation run:
  PowerTOST version: 1.5-7
  R script: scripts/powertost_crossval.R

Reference:
  Labes D, Schutz H, Lang B (2024). PowerTOST: Power and Sample Size
  for (Bio)Equivalence Studies. R package, CRAN.

  Phillips KF (1990). Power of the two one-sided tests procedure in
  bioequivalence. J Pharmacokinet Biopharm, 18(2):137-144.
  DOI: 10.1007/BF01063556

  Diletti E, Hauschke D, Steinijans VW (1991). Sample size determination
  for bioequivalence assessment by means of confidence intervals.
  Int J Clin Pharmacol Ther Toxicol, 29(1):1-8.

Formula (both PowerTOST and openpkflow):
  Exact non-central t-distribution (Owen's Q):
    power = 1 - F_nct(t_crit, df, delta_u) - F_nct(t_crit, df, delta_l)
  where sigma_w = sqrt(log(1 + CV^2)), se = sigma_w * sqrt(2/n), df = n - 2.
  Matches PowerTOST power.TOST(method="exact") to < 1e-5 in probability
  units across 6 diverse scenarios.

Degenerate properties:
  - power -> 1.0 as n -> inf for GMR=1.0 (large-sample behavior)
  - power -> alpha when GMR is at the acceptance limit (size of the test)
  - sample size decreases as CV decreases (higher precision requires fewer subjects)
"""

from __future__ import annotations

import pytest

from openpkflow.be.methods import be_sample_size, be_tost_power

# ---------------------------------------------------------------------------
# PowerTOST 1.5-7 reference values
#
# Generated by: Rscript scripts/powertost_crossval.R
# power.TOST(method="exact", design="2x2") at default FDA limits (0.80-1.25, alpha=0.05)
# ---------------------------------------------------------------------------

_POWERTOST_POWER_REFERENCE: dict[str, dict[str, object]] = {
    "1": {"GMR": 0.95, "CV": 0.15, "n": 24, "power": 0.986761},
    "2": {"GMR": 1.00, "CV": 0.20, "n": 18, "power": 0.887592},
    "3": {"GMR": 0.90, "CV": 0.25, "n": 36, "power": 0.634540},
    "4": {"GMR": 1.05, "CV": 0.10, "n": 12, "power": 0.989960},
    "5": {"GMR": 0.80, "CV": 0.30, "n": 48, "power": 0.050000},
    "6": {"GMR": 0.95, "CV": 0.35, "n": 40, "power": 0.688789},
}

_POWERTOST_SAMPLE_SIZE_REFERENCE: dict[str, dict[str, object]] = {
    "1": {"target_power": 0.80, "GMR": 0.95, "CV": 0.20, "n": 20, "achieved_power": 0.8346801909},
    "2": {"target_power": 0.90, "GMR": 0.95, "CV": 0.15, "n": 16, "achieved_power": 0.9260213185},
    "3": {"target_power": 0.80, "GMR": 0.90, "CV": 0.25, "n": 56, "achieved_power": 0.8035816681},
    "4": {"target_power": 0.80, "GMR": 1.00, "CV": 0.10, "n": 6, "achieved_power": 0.8652044666},
    "5": {"target_power": 0.90, "GMR": 0.95, "CV": 0.30, "n": 52, "achieved_power": 0.9019649888},
    "6": {"target_power": 0.80, "GMR": 0.85, "CV": 0.15, "n": 78, "achieved_power": 0.8080020738},
}


class TestPowerTOSTCrossValidation:
    """Verify openpkflow be_tost_power() and be_sample_size() match PowerTOST 1.5-7.

    Labes D, Schutz H, Lang B (2024). PowerTOST. CRAN.
    Phillips KF (1990). J Pharmacokinet Biopharm 18(2):137-144.
    Diletti E et al. (1991). Int J Clin Pharmacol Ther Toxicol 29(1):1-8.
    """

    def test_power_matches_powertost_scenario_1(self) -> None:
        s = _POWERTOST_POWER_REFERENCE["1"]
        result = be_tost_power(float(s["GMR"]), float(s["CV"]), int(s["n"]))
        assert result == pytest.approx(float(s["power"]), abs=1e-5)

    def test_power_matches_powertost_scenario_2(self) -> None:
        s = _POWERTOST_POWER_REFERENCE["2"]
        result = be_tost_power(float(s["GMR"]), float(s["CV"]), int(s["n"]))
        assert result == pytest.approx(float(s["power"]), abs=1e-5)

    def test_power_matches_powertost_scenario_3(self) -> None:
        s = _POWERTOST_POWER_REFERENCE["3"]
        result = be_tost_power(float(s["GMR"]), float(s["CV"]), int(s["n"]))
        assert result == pytest.approx(float(s["power"]), abs=1e-5)

    def test_power_matches_powertost_scenario_4(self) -> None:
        s = _POWERTOST_POWER_REFERENCE["4"]
        result = be_tost_power(float(s["GMR"]), float(s["CV"]), int(s["n"]))
        assert result == pytest.approx(float(s["power"]), abs=1e-5)

    def test_power_matches_powertost_scenario_5(self) -> None:
        s = _POWERTOST_POWER_REFERENCE["5"]
        result = be_tost_power(float(s["GMR"]), float(s["CV"]), int(s["n"]))
        assert result == pytest.approx(float(s["power"]), abs=1e-5)

    def test_power_matches_powertost_scenario_6(self) -> None:
        s = _POWERTOST_POWER_REFERENCE["6"]
        result = be_tost_power(float(s["GMR"]), float(s["CV"]), int(s["n"]))
        assert result == pytest.approx(float(s["power"]), abs=1e-5)

    def test_sample_size_matches_powertost_scenario_1(self) -> None:
        s = _POWERTOST_SAMPLE_SIZE_REFERENCE["1"]
        n, pw = be_sample_size(float(s["GMR"]), float(s["CV"]), float(s["target_power"]))
        assert n == int(s["n"])
        assert pw == pytest.approx(float(s["achieved_power"]), abs=1e-5)

    def test_sample_size_matches_powertost_scenario_2(self) -> None:
        s = _POWERTOST_SAMPLE_SIZE_REFERENCE["2"]
        n, pw = be_sample_size(float(s["GMR"]), float(s["CV"]), float(s["target_power"]))
        assert n == int(s["n"])
        assert pw == pytest.approx(float(s["achieved_power"]), abs=1e-5)

    def test_sample_size_matches_powertost_scenario_3(self) -> None:
        s = _POWERTOST_SAMPLE_SIZE_REFERENCE["3"]
        n, pw = be_sample_size(float(s["GMR"]), float(s["CV"]), float(s["target_power"]))
        assert n == int(s["n"])
        assert pw == pytest.approx(float(s["achieved_power"]), abs=1e-5)

    def test_sample_size_matches_powertost_scenario_4(self) -> None:
        s = _POWERTOST_SAMPLE_SIZE_REFERENCE["4"]
        n, pw = be_sample_size(float(s["GMR"]), float(s["CV"]), float(s["target_power"]))
        assert n == int(s["n"])
        assert pw == pytest.approx(float(s["achieved_power"]), abs=1e-5)

    def test_sample_size_matches_powertost_scenario_5(self) -> None:
        s = _POWERTOST_SAMPLE_SIZE_REFERENCE["5"]
        n, pw = be_sample_size(float(s["GMR"]), float(s["CV"]), float(s["target_power"]))
        assert n == int(s["n"])
        assert pw == pytest.approx(float(s["achieved_power"]), abs=1e-5)

    def test_sample_size_matches_powertost_scenario_6(self) -> None:
        s = _POWERTOST_SAMPLE_SIZE_REFERENCE["6"]
        n, pw = be_sample_size(float(s["GMR"]), float(s["CV"]), float(s["target_power"]))
        assert n == int(s["n"])
        assert pw == pytest.approx(float(s["achieved_power"]), abs=1e-5)

    def test_power_approaches_one_as_n_grows_for_gmr_one(self) -> None:
        pwr = be_tost_power(gmr=1.0, cv=0.15, n=100)
        assert pwr > 0.999

    def test_power_equals_alpha_at_boundary_gmr(self) -> None:
        pwr = be_tost_power(gmr=0.80, cv=0.15, n=50)
        assert pwr == pytest.approx(0.05, abs=0.01)

    def test_power_increases_with_n(self) -> None:
        p20 = be_tost_power(gmr=0.95, cv=0.20, n=20)
        p40 = be_tost_power(gmr=0.95, cv=0.20, n=40)
        assert p40 > p20

    def test_power_decreases_with_higher_cv(self) -> None:
        p_low = be_tost_power(gmr=0.95, cv=0.10, n=24)
        p_high = be_tost_power(gmr=0.95, cv=0.30, n=24)
        assert p_low > p_high

    def test_sample_size_decreases_as_cv_decreases(self) -> None:
        n_low, _ = be_sample_size(gmr=0.95, cv=0.15, target_power=0.80)
        n_high, _ = be_sample_size(gmr=0.95, cv=0.30, target_power=0.80)
        assert n_low < n_high

    def test_sample_size_higher_for_gmr_farther_from_one(self) -> None:
        n_095, _ = be_sample_size(gmr=0.95, cv=0.20, target_power=0.80)
        n_090, _ = be_sample_size(gmr=0.90, cv=0.20, target_power=0.80)
        assert n_090 > n_095

    def test_power_raises_on_invalid_gmr(self) -> None:
        with pytest.raises(ValueError):
            be_tost_power(gmr=-1.0, cv=0.20, n=24)
        with pytest.raises(ValueError):
            be_tost_power(gmr=0.0, cv=0.20, n=24)

    def test_power_raises_on_invalid_cv(self) -> None:
        with pytest.raises(ValueError):
            be_tost_power(gmr=1.0, cv=0.0, n=24)
        with pytest.raises(ValueError):
            be_tost_power(gmr=1.0, cv=-0.1, n=24)

    def test_power_raises_on_small_n(self) -> None:
        with pytest.raises(ValueError):
            be_tost_power(gmr=1.0, cv=0.20, n=2)

    def test_sample_size_raises_on_invalid_target_power(self) -> None:
        with pytest.raises(ValueError):
            be_sample_size(gmr=1.0, cv=0.20, target_power=0.0)
        with pytest.raises(ValueError):
            be_sample_size(gmr=1.0, cv=0.20, target_power=1.0)
        with pytest.raises(ValueError):
            be_sample_size(gmr=1.0, cv=0.20, target_power=1.5)

    def test_power_is_between_zero_and_one(self) -> None:
        scenarios = [
            (0.95, 0.15, 24),
            (1.00, 0.10, 12),
            (0.80, 0.30, 48),
            (1.10, 0.25, 36),
        ]
        for gmr, cv, n in scenarios:
            pwr = be_tost_power(gmr, cv, n)
            assert 0.0 <= pwr <= 1.0
