"""Dissolution validation: bootf2 cross-validation of f1 and f2.

bootf2 cross-validation run:
  bootf2 version: 0.4.1
  Dataset: src/openpkflow/datasets/example_dissolution.csv
           3 reference batches (R1-R3), 3 test batches (T1-T3)
           6 time points: 5, 10, 15, 20, 30, 45 min
  R script: scripts/bootf2_dissolution_crossval.R

Reference:
  Zhu H (2022). bootf2: Bootstrap f2 Similarity Factor.
  R package, CRAN.

  FDA Guidance for Industry: Dissolution Testing of Immediate Release
  Solid Oral Dosage Forms (1997).

Formula (both bootf2 and openpkflow):
  f2 = 50 * log10(100 / sqrt(1 + (1/n) * sum((Rt - Tt)^2)))
  where Rt and Tt are per-time-point means across batches.

bootf2's calcf2() f2.type="est.f2" is algebraically identical to
openpkflow's f2(..., method="all_points"). Values match to floating-point
precision (< 1e-10 relative difference).

Degenerate properties also tested (FDA 1997 guidance):
  - f2 = 100 when reference == test (identical profiles)
  - f1 = 0  when reference == test
  - f2 >= 50 indicates similarity (FDA threshold)
"""

from __future__ import annotations

import math

import pytest

from openpkflow.dissolution.similarity import f1, f2

# ---------------------------------------------------------------------------
# bootf2 0.4.1 reference values
#
# Generated by: Rscript scripts/bootf2_dissolution_crossval.R
# f2 computed from per-time-point batch means (est.f2 = regulatory formula).
# ---------------------------------------------------------------------------

_BOOTF2_REFERENCE: dict[str, object] = {
    "example_dissolution_all_points": 57.873301,
    "n_timepoints": 6,
    "ref_means": [15.000000, 30.000000, 48.000000, 62.033333, 78.000000, 90.033333],
    "test_means": [12.066667, 24.033333, 40.000000, 54.966667, 70.066667, 82.066667],
}

# Published reference datasets for degenerate checks (FDA 1997)
_SIMILAR_REF = [20.0, 38.0, 55.0, 68.0, 82.0, 93.0]
_SIMILAR_TST = [21.0, 37.0, 54.0, 69.0, 81.0, 92.0]  # f2 ~ 92.5 (clearly similar)

_NOT_SIMILAR_REF = [20.0, 38.0, 55.0, 68.0, 82.0, 93.0]
_NOT_SIMILAR_TST = [12.0, 25.0, 38.0, 52.0, 68.0, 80.0]  # f2 ~ 42.9 (not similar)


class TestBootf2CrossValidation:
    """Verify openpkflow f2() matches bootf2 0.4.1 calcf2(est.f2).

    Zhu H (2022). bootf2. CRAN.
    FDA (1997). Dissolution Testing of Immediate Release Solid Oral Dosage Forms.
    """

    def test_f2_matches_bootf2_example_dataset(self) -> None:
        ref = _BOOTF2_REFERENCE["ref_means"]
        tst = _BOOTF2_REFERENCE["test_means"]
        expected = _BOOTF2_REFERENCE["example_dissolution_all_points"]
        result = f2(ref, tst, method="all_points")
        assert result == pytest.approx(expected, rel=1e-5), (
            f"f2={result:.6f} vs bootf2={expected:.6f}"
        )

    def test_f2_identical_profiles_is_100(self) -> None:
        profile = [20.0, 40.0, 60.0, 80.0, 90.0]
        assert f2(profile, profile, method="all_points") == pytest.approx(100.0, abs=1e-6)

    def test_f1_identical_profiles_is_zero(self) -> None:
        profile = [20.0, 40.0, 60.0, 80.0, 90.0]
        assert f1(profile, profile) == pytest.approx(0.0, abs=1e-10)

    def test_f2_similar_profiles_above_50(self) -> None:
        result = f2(_SIMILAR_REF, _SIMILAR_TST, method="all_points")
        assert result == pytest.approx(92.474250, rel=1e-5)
        assert result >= 50.0, f"f2={result:.2f} should be >= 50 for similar profiles"

    def test_f2_not_similar_profiles_below_50(self) -> None:
        result = f2(_NOT_SIMILAR_REF, _NOT_SIMILAR_TST, method="all_points")
        assert result == pytest.approx(42.945781, rel=1e-5)
        assert result < 50.0, f"f2={result:.2f} should be < 50 for dissimilar profiles"

    def test_f1_similar_profiles_near_zero(self) -> None:
        result = f1(_SIMILAR_REF, _SIMILAR_TST)
        assert result == pytest.approx(1.685393, rel=1e-5)
        assert result < 15.0, f"f1={result:.2f} should be low for similar profiles"

    def test_f1_not_similar_profiles_high(self) -> None:
        result = f1(_NOT_SIMILAR_REF, _NOT_SIMILAR_TST)
        assert result == pytest.approx(22.752809, rel=1e-5)
        assert result > 15.0, f"f1={result:.2f} should be elevated for dissimilar profiles"

    def test_f2_formula_matches_manual_calculation(self) -> None:
        ref = _BOOTF2_REFERENCE["ref_means"]
        tst = _BOOTF2_REFERENCE["test_means"]
        n = len(ref)
        sq_diff = sum((r - t) ** 2 for r, t in zip(ref, tst, strict=False))
        expected = 50 * math.log10(100 / math.sqrt(1 + sq_diff / n))
        result = f2(ref, tst, method="all_points")
        assert result == pytest.approx(expected, rel=1e-10)

    def test_n_timepoints_matches_reference(self) -> None:
        ref = _BOOTF2_REFERENCE["ref_means"]
        assert len(ref) == _BOOTF2_REFERENCE["n_timepoints"]

    def test_f2_decreases_as_profiles_diverge(self) -> None:
        base = [20.0, 40.0, 60.0, 80.0, 90.0]
        small_diff = [21.0, 41.0, 61.0, 81.0, 91.0]
        large_diff = [30.0, 50.0, 70.0, 85.0, 92.0]
        assert f2(base, small_diff, method="all_points") > f2(base, large_diff, method="all_points")
