"""Sparse NCA cross-validation against base R nonlinear least squares."""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from openpkflow.datasets import example_theoph_path
from openpkflow.nca import fit_sparse_1cmt_oral

_TIMES = np.array([0.25, 1.12, 3.82, 9.05, 24.37])
_R_COEFFICIENTS = {
    "CL_F": 1.58688395036511,
    "Vz_F": 28.61058743867474,
    "ka": 1.77941295907683,
}
_R_FITTED = np.array(
    [
        3.98645036460128,
        9.27573859783137,
        9.32737313350116,
        6.98840914532874,
        2.98777968039786,
    ]
)


def test_sparse_theoph_matches_r_nls_port_reference() -> None:
    """Match R 4.6.0 stats::nls on the published nlme::Theoph dataset.

    Reference: R ``nlme::Theoph`` dataset; independent fit generated by
    ``scripts/sparse_nca_theoph_crossval.R`` using ``stats::nls`` with the
    bounded ``port`` algorithm. The dataset originates from Boeckmann,
    Sheiner, and Beal, NONMEM Users Guide Part V (1994).
    """
    data = pd.read_csv(example_theoph_path())
    profile = data[(data["subject"] == 1) & data["time"].isin(_TIMES)]

    result = fit_sparse_1cmt_oral(
        profile["time"].to_numpy(),
        profile["conc"].to_numpy(),
        dose=320.0,
        p0=(3.0, 30.0, 2.0),
    )

    assert result.converged is True
    assert pytest.approx(_R_COEFFICIENTS["CL_F"], rel=1e-4) == result.CL_F
    assert pytest.approx(_R_COEFFICIENTS["Vz_F"], rel=1e-4) == result.Vz_F
    assert pytest.approx(_R_COEFFICIENTS["ka"], rel=1e-4) == result.ka
    assert pytest.approx(_R_FITTED, rel=1e-4) == result.fitted_conc
