"""NCA validation: PKNCA-R cross-validation of steady-state parameters.

PKNCA cross-validation run:
  PKNCA version: 0.12.1
  AUC method: linear-up/log-down
  Dataset: src/openpkflow/datasets/ss_crossval.csv
           3 synthetic subjects (1-cmt oral SS model, tau=8 h)
  R script: scripts/pknca_ss_crossval.R

Reference:
  Denney WS, Duvvuri S, Buckeridge CE (2015).
  "Simple, Automatic Noncompartmental Analysis: The PKNCA R Package."
  Journal of Statistical Software, 59(1), 1-21. DOI: 10.18637/jss.v059.i11

Synthetic dataset:
  Generated from the 1-compartment oral steady-state equation:
    C_ss(t) = (F*D*ka) / (V*(ka-ke)) * [exp(-ke*t)/(1-exp(-ke*tau))
                                        - exp(-ka*t)/(1-exp(-ka*tau))]
  where ke = CL/V.  C(0) == C(tau) to machine precision (verified).

  Subject parameters:
    SS1: CL=5, V=30, ka=1.5, dose=100, tau=8
    SS2: CL=3, V=25, ka=1.0, dose=100, tau=8
    SS3: CL=8, V=40, ka=2.0, dose=100, tau=8

Parameters cross-validated:
  AUCtau, Cmax_ss, Cmin_ss, Cavg_ss, fluctuation_pct, swing

Unit note:
  PKNCA returns swing with unit_type "%" (i.e., ratio * 100).
  openpkflow returns swing as a dimensionless ratio ((Cmax-Cmin)/Cmin).
  The reference dict below stores swing as a ratio (PKNCA value / 100).

Tolerance:
  2% relative for all continuous parameters (values agree to 4+ decimals).
"""

from __future__ import annotations

import pytest

from openpkflow.nca.study import NCAStudy

# ---------------------------------------------------------------------------
# PKNCA 0.12.1 reference values
#
# Generated by: Rscript scripts/pknca_ss_crossval.R
# swing converted from PKNCA percent to ratio (divided by 100).
# ---------------------------------------------------------------------------

_PKNCA_SS_REFERENCE: dict[str, dict[str, float]] = {
    "SS1": {
        "AUCtau": 19.874213,
        "Cmax_ss": 3.570654,
        "Cmin_ss": 1.342298,
        "Cavg_ss": 2.484277,
        "fluctuation_pct": 89.698385,
        "swing": 1.66010495,  # PKNCA 166.010495 / 100
    },
    "SS2": {
        "AUCtau": 33.200146,
        "Cmax_ss": 5.178735,
        "Cmin_ss": 2.818767,
        "Cavg_ss": 4.150018,
        "fluctuation_pct": 56.866448,
        "swing": 0.83723428,  # PKNCA 83.723428 / 100
    },
    "SS3": {
        "AUCtau": 12.385842,
        "Cmax_ss": 2.473639,
        "Cmin_ss": 0.702695,
        "Cavg_ss": 1.548230,
        "fluctuation_pct": 114.385048,
        "swing": 2.52021670,  # PKNCA 252.021670 / 100
    },
}

_SS_TOL = 0.02  # 2% relative tolerance


# ---------------------------------------------------------------------------
# Fixture
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def ss_summary():
    from openpkflow.datasets import example_ss_crossval_path

    study = NCAStudy.from_csv(
        example_ss_crossval_path(),
        auc_method="linear_up_log_down",
        blq_method="none",
        steady_state=True,
        tau=8.0,
    )
    return study.analyze()


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestPKNCASSCrossValidation:
    """Verify steady-state NCA parameters match PKNCA 0.12.1 within 2%.

    Dataset: 3-subject synthetic 1-cmt oral steady-state (tau=8 h).
    Denney WS et al. (2015). DOI: 10.18637/jss.v059.i11
    """

    def _check(
        self,
        results: list,
        attr: str,
        ref_key: str,
        *,
        absolute: bool = False,
    ) -> None:
        failures = []
        for r in results:
            ref_val = _PKNCA_SS_REFERENCE[r.subject][ref_key]
            obs_val = getattr(r, attr)
            if obs_val is None:
                failures.append(f"Subject {r.subject}: {attr} is None")
                continue
            diff = abs(obs_val - ref_val)
            denom = abs(ref_val) if not absolute else 1.0
            if denom > 0 and diff / denom > _SS_TOL:
                failures.append(
                    f"Subject {r.subject}: {attr}={obs_val:.6f} vs PKNCA={ref_val:.6f} "
                    f"({'abs' if absolute else 'rel'} diff={diff / denom:.4%})"
                )
        assert not failures, "\n".join(failures)

    def test_all_3_subjects_present(self, ss_summary) -> None:
        subjects = sorted(r.subject for r in ss_summary.results)
        assert subjects == sorted(_PKNCA_SS_REFERENCE.keys())

    def test_ss_params_populated(self, ss_summary) -> None:
        for r in ss_summary.results:
            assert r.AUCtau is not None, f"{r.subject}: AUCtau is None"
            assert r.Cmax_ss is not None, f"{r.subject}: Cmax_ss is None"
            assert r.Cmin_ss is not None, f"{r.subject}: Cmin_ss is None"
            assert r.Cavg_ss is not None, f"{r.subject}: Cavg_ss is None"
            assert r.fluctuation_pct is not None, f"{r.subject}: fluctuation_pct is None"
            assert r.swing is not None, f"{r.subject}: swing is None"

    def test_auctau_matches_pknca(self, ss_summary) -> None:
        self._check(ss_summary.results, "AUCtau", "AUCtau")

    def test_cmax_ss_matches_pknca(self, ss_summary) -> None:
        self._check(ss_summary.results, "Cmax_ss", "Cmax_ss")

    def test_cmin_ss_matches_pknca(self, ss_summary) -> None:
        self._check(ss_summary.results, "Cmin_ss", "Cmin_ss")

    def test_cavg_ss_matches_pknca(self, ss_summary) -> None:
        self._check(ss_summary.results, "Cavg_ss", "Cavg_ss")

    def test_fluctuation_pct_matches_pknca(self, ss_summary) -> None:
        self._check(ss_summary.results, "fluctuation_pct", "fluctuation_pct")

    def test_swing_matches_pknca(self, ss_summary) -> None:
        # openpkflow swing is a ratio; PKNCA swing is a % (/ 100 in reference dict)
        self._check(ss_summary.results, "swing", "swing")

    def test_cavg_equals_auctau_over_tau(self, ss_summary) -> None:
        tau = 8.0
        for r in ss_summary.results:
            expected = r.AUCtau / tau
            assert r.Cavg_ss == pytest.approx(expected, rel=1e-6), (
                f"{r.subject}: Cavg_ss={r.Cavg_ss} != AUCtau/tau={expected}"
            )

    def test_fluctuation_formula_consistent(self, ss_summary) -> None:
        for r in ss_summary.results:
            expected = (r.Cmax_ss - r.Cmin_ss) / r.Cavg_ss * 100.0
            assert r.fluctuation_pct == pytest.approx(expected, rel=1e-6), (
                f"{r.subject}: fluctuation_pct={r.fluctuation_pct} vs formula={expected}"
            )

    def test_swing_formula_consistent(self, ss_summary) -> None:
        for r in ss_summary.results:
            expected = (r.Cmax_ss - r.Cmin_ss) / r.Cmin_ss
            assert r.swing == pytest.approx(expected, rel=1e-6), (
                f"{r.subject}: swing={r.swing} vs formula={expected}"
            )
