"""NCA validation: NonCompart 0.8.x cross-validation on the theophylline dataset.

This is a second, independent cross-validation alongside PKNCA 0.12.1.
Three-way agreement (openpkflow == PKNCA == NonCompart) on all 12 subjects
and all parameters is the strongest available open-source NCA validation claim.

NonCompart cross-validation run:
  NonCompart version: 0.8.0
  AUC method: linear-up/log-down (down="Log")
  Dataset: src/openpkflow/datasets/theoph.csv (12 subjects, oral theophylline)
  R script: scripts/noncompart_theoph_crossval.R

Reference:
  Kim S, Kim J (2024). NonCompart: Noncompartmental Analysis for
  Pharmacokinetic Data. R package, CRAN.

Unit note:
  When concUnit="mg/L" is passed to sNCA(), NonCompart returns CL in L/h
  and V in L (dose_mg / AUC_mg*h/L = L/h).  Without concUnit, NonCompart
  defaults to mL/h and mL (1000x larger).

All NonCompart values are identical to PKNCA 0.12.1 and openpkflow to
4+ decimal places, confirming three-way agreement across independent
implementations.

Tolerance: 2% relative for all continuous parameters.
"""

from __future__ import annotations

import pytest

from openpkflow.datasets import example_theoph_path
from openpkflow.nca.study import NCAStudy

# ---------------------------------------------------------------------------
# NonCompart 0.8.0 reference values (all 12 subjects)
#
# Generated by: Rscript scripts/noncompart_theoph_crossval.R
# ---------------------------------------------------------------------------

_NONCOMPART_REFERENCE: dict[str, dict[str, float | int]] = {
    "1": {
        "AUClast": 147.234749,
        "Cmax": 10.500000,
        "Tmax": 1.1200,
        "AUCinf_obs": 214.923632,
        "AUC_pct_extrap": 31.4944,
        "half_life": 14.304378,
        "lambda_z": 0.04845700,
        "adj_r2": 0.999999,
        "n_points": 3,
        "CL_F": 1.488901,
        "Vz_F": 30.726232,
    },
    "2": {
        "AUClast": 88.206965,
        "Cmax": 8.330000,
        "Tmax": 1.9200,
        "AUCinf_obs": 96.690714,
        "AUC_pct_extrap": 8.7741,
        "half_life": 6.533874,
        "lambda_z": 0.10608518,
        "adj_r2": 0.996372,
        "n_points": 4,
        "CL_F": 3.294629,
        "Vz_F": 31.056446,
    },
    "3": {
        "AUClast": 95.878198,
        "Cmax": 8.200000,
        "Tmax": 1.0200,
        "AUCinf_obs": 106.127669,
        "AUC_pct_extrap": 9.6577,
        "half_life": 6.766087,
        "lambda_z": 0.10244431,
        "adj_r2": 0.998650,
        "n_points": 3,
        "CL_F": 3.009300,
        "Vz_F": 29.374984,
    },
    "4": {
        "AUClast": 102.633623,
        "Cmax": 8.600000,
        "Tmax": 1.0700,
        "AUCinf_obs": 114.216205,
        "AUC_pct_extrap": 10.1409,
        "half_life": 6.981247,
        "lambda_z": 0.09928702,
        "adj_r2": 0.997848,
        "n_points": 3,
        "CL_F": 2.800653,
        "Vz_F": 28.207649,
    },
    "5": {
        "AUClast": 118.179354,
        "Cmax": 11.400000,
        "Tmax": 1.0000,
        "AUCinf_obs": 136.304732,
        "AUC_pct_extrap": 13.2977,
        "half_life": 8.002264,
        "lambda_z": 0.08661888,
        "adj_r2": 0.997971,
        "n_points": 4,
        "CL_F": 2.347387,
        "Vz_F": 27.100180,
    },
    "6": {
        "AUClast": 72.572307,
        "Cmax": 6.440000,
        "Tmax": 1.0200,
        "AUCinf_obs": 83.315478,
        "AUC_pct_extrap": 12.8946,
        "half_life": 8.094128,
        "lambda_z": 0.08563580,
        "adj_r2": 0.999145,
        "n_points": 7,
        "CL_F": 3.840823,
        "Vz_F": 44.850669,
    },
    "7": {
        "AUClast": 87.813694,
        "Cmax": 7.540000,
        "Tmax": 2.1300,
        "AUCinf_obs": 94.628698,
        "AUC_pct_extrap": 7.2018,
        "half_life": 6.056155,
        "lambda_z": 0.11445335,
        "adj_r2": 0.999123,
        "n_points": 4,
        "CL_F": 3.379207,
        "Vz_F": 29.524759,
    },
    "8": {
        "AUClast": 104.126247,
        "Cmax": 8.730000,
        "Tmax": 3.4800,
        "AUCinf_obs": 114.637319,
        "AUC_pct_extrap": 9.1690,
        "half_life": 6.505107,
        "lambda_z": 0.10655431,
        "adj_r2": 0.999982,
        "n_points": 3,
        "CL_F": 2.785917,
        "Vz_F": 26.145507,
    },
    "9": {
        "AUClast": 51.542491,
        "Cmax": 9.030000,
        "Tmax": 0.6300,
        "AUCinf_obs": 83.827552,
        "AUC_pct_extrap": 38.5137,
        "half_life": 7.534781,
        "lambda_z": 0.09199301,
        "adj_r2": 0.893189,
        "n_points": 7,
        "CL_F": 3.195131,
        "Vz_F": 34.732322,
    },
    "10": {
        "AUClast": 135.576070,
        "Cmax": 10.210000,
        "Tmax": 3.5500,
        "AUCinf_obs": 167.860031,
        "AUC_pct_extrap": 19.2327,
        "half_life": 9.246916,
        "lambda_z": 0.07495982,
        "adj_r2": 0.999017,
        "n_points": 3,
        "CL_F": 1.906946,
        "Vz_F": 25.439573,
    },
    "11": {
        "AUClast": 78.507777,
        "Cmax": 8.000000,
        "Tmax": 0.9800,
        "AUCinf_obs": 87.564755,
        "AUC_pct_extrap": 10.3432,
        "half_life": 7.299790,
        "lambda_z": 0.09495441,
        "adj_r2": 0.999579,
        "n_points": 4,
        "CL_F": 3.652154,
        "Vz_F": 38.462189,
    },
    "12": {
        "AUClast": 99.947668,
        "Cmax": 9.750000,
        "Tmax": 2.0200,
        "AUCinf_obs": 113.248990,
        "AUC_pct_extrap": 11.7452,
        "half_life": 7.375819,
        "lambda_z": 0.09397562,
        "adj_r2": 0.976270,
        "n_points": 6,
        "CL_F": 2.831372,
        "Vz_F": 30.128790,
    },
}

_TOL = 0.02


# ---------------------------------------------------------------------------
# Fixture
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def theoph_summary():
    study = NCAStudy.from_csv(
        example_theoph_path(),
        auc_method="linear_up_log_down",
        blq_method="none",
    )
    return study.analyze()


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestNonCompartCrossValidation:
    """Verify openpkflow matches NonCompart 0.8.0 within 2% on all 12 theoph subjects.

    Together with PKNCA 0.12.1 agreement (test_nca_theoph_reference.py) this
    constitutes three-way cross-validation: the strongest available open-source
    NCA validation claim.

    Kim S, Kim J (2024). NonCompart. CRAN.
    """

    def _check(self, results: list, attr: str, ref_key: str) -> None:
        failures = []
        for r in results:
            ref_val = _NONCOMPART_REFERENCE[r.subject][ref_key]
            obs_val = getattr(r, attr)
            if obs_val is None:
                failures.append(f"Subject {r.subject}: {attr} is None")
                continue
            diff = abs(obs_val - ref_val)
            denom = abs(ref_val) if ref_val != 0 else 1.0
            if diff / denom > _TOL:
                failures.append(
                    f"Subject {r.subject}: {attr}={obs_val:.6f} vs "
                    f"NonCompart={ref_val:.6f} (rel diff={diff / denom:.4%})"
                )
        assert not failures, "\n".join(failures)

    def test_all_12_subjects_present(self, theoph_summary) -> None:
        subjects = sorted(r.subject for r in theoph_summary.results)
        assert subjects == sorted(_NONCOMPART_REFERENCE.keys())

    def test_auclast_matches_noncompart(self, theoph_summary) -> None:
        self._check(theoph_summary.results, "AUClast", "AUClast")

    def test_cmax_matches_noncompart(self, theoph_summary) -> None:
        self._check(theoph_summary.results, "Cmax", "Cmax")

    def test_tmax_matches_noncompart(self, theoph_summary) -> None:
        for r in theoph_summary.results:
            ref = _NONCOMPART_REFERENCE[r.subject]["Tmax"]
            assert r.Tmax == pytest.approx(ref, abs=1e-4), (
                f"Subject {r.subject}: Tmax={r.Tmax} vs NonCompart={ref}"
            )

    def test_aucinf_obs_matches_noncompart(self, theoph_summary) -> None:
        self._check(theoph_summary.results, "AUCinf_obs", "AUCinf_obs")

    def test_auc_pct_extrap_matches_noncompart(self, theoph_summary) -> None:
        failures = []
        for r in theoph_summary.results:
            ref_val = _NONCOMPART_REFERENCE[r.subject]["AUC_pct_extrap"]
            obs_val = r.AUC_percent_extrapolated
            if obs_val is None:
                failures.append(f"Subject {r.subject}: AUC_percent_extrapolated is None")
                continue
            if abs(obs_val - ref_val) > 0.005:  # 0.5 percentage point absolute
                failures.append(f"Subject {r.subject}: {obs_val:.4f} vs NonCompart={ref_val:.4f}")
        assert not failures, "\n".join(failures)

    def test_half_life_matches_noncompart(self, theoph_summary) -> None:
        self._check(theoph_summary.results, "half_life", "half_life")

    def test_lambda_z_matches_noncompart(self, theoph_summary) -> None:
        self._check(theoph_summary.results, "lambda_z", "lambda_z")

    def test_adj_r2_matches_noncompart(self, theoph_summary) -> None:
        failures = []
        for r in theoph_summary.results:
            ref_val = _NONCOMPART_REFERENCE[r.subject]["adj_r2"]
            obs_val = r.lambda_z_adj_r2
            if obs_val is None:
                failures.append(f"Subject {r.subject}: lambda_z_adj_r2 is None")
                continue
            if abs(obs_val - ref_val) > 0.01:
                failures.append(
                    f"Subject {r.subject}: adj_r2={obs_val:.6f} vs NonCompart={ref_val:.6f}"
                )
        assert not failures, "\n".join(failures)

    def test_n_points_matches_noncompart_exactly(self, theoph_summary) -> None:
        for r in theoph_summary.results:
            ref = int(_NONCOMPART_REFERENCE[r.subject]["n_points"])
            assert r.lambda_z_n_points == ref, (
                f"Subject {r.subject}: n_points={r.lambda_z_n_points} vs NonCompart={ref}"
            )

    def test_cl_f_matches_noncompart(self, theoph_summary) -> None:
        self._check(theoph_summary.results, "CL_F", "CL_F")

    def test_vz_f_matches_noncompart(self, theoph_summary) -> None:
        self._check(theoph_summary.results, "Vz_F", "Vz_F")
