"""IVIVC Level A cross-validation: Wagner-Nelson and Loo-Riegelman.

Independent R implementation cross-validation run:
  R script: scripts/ivivc_wn_lr_crossval.R
  Strategy: formula-level algebraic identity (no external R packages).
  Both R and openpkflow implement the same FDA-defined formulas directly.
  Values should match to floating-point precision (< 1e-10 relative difference).

References:
  Wagner JG, Nelson E (1963). J Pharm Sci, 52(6):610-611.
    DOI: 10.1002/jps.2600520624
  Loo JCK, Riegelman S (1968). J Pharm Sci, 57(6):918-928.
    DOI: 10.1002/jps.2600570602
  Gibaldi M, Perrier D (1982). Pharmacokinetics, 2nd ed. Marcel Dekker.
    Chapter 4, pp. 149-151 (Wagner-Nelson example).
  FDA Guidance for Industry: Extended Release Oral Dosage Forms: Development,
    Evaluation, and Application of In Vitro/In Vivo Correlations (1997), CDER.

Formulas (both R and openpkflow):
  Wagner-Nelson (1-cmt): F_a(t) = [C(t) + kel*AUC(0,t)] / [kel*AUC(0,inf)]
    where AUC(0,inf) = AUC_last + C_last/kel  (linear trapezoidal + extrapolation)

  Loo-Riegelman (2-cmt): F_a(t) = [C(t) + k10*AUC(0,t)
    + k12*exp(-k21*t)*AUC_exp(t)] / [k10*AUC(0,inf)]
    where AUC_exp = cumulative integral of C(tau)*exp(k21*tau)

Note on Loo-Riegelman F_a > 1.0:
  The LR formula does not guarantee F_a <= 1.0; values exceeding 1.0 are
  mathematically correct artifacts of the peripheral compartment term and the
  AUC_inf normalization based on plasma only.  This is a known property of the
  method (see Gibaldi & Perrier Chapter 4).
"""

from __future__ import annotations

import numpy as np
import pytest

from openpkflow.ivivc.methods import loo_riegelman, wagner_nelson

# ---------------------------------------------------------------------------
# R cross-validation reference values
#
# Generated by: Rscript scripts/ivivc_wn_lr_crossval.R
# Formulas implemented independently in R (no external packages).
# ---------------------------------------------------------------------------

_WN_GP_REFERENCE: dict[str, object] = {
    "times": [0.5, 1.0, 2.0, 3.0, 4.0, 6.0, 8.0, 12.0],
    "concs": [3.2, 5.8, 9.4, 10.8, 11.0, 9.6, 7.2, 3.5],
    "kel": 0.15,
    "fa": [
        0.1888184098,
        0.3621478094,
        0.6418350789,
        0.8138368491,
        0.9221124060,
        1.0218321286,
        1.0289128190,
        1.0000000000,
    ],
}

_LR_REFERENCE: dict[str, object] = {
    "times": [0.5, 1.0, 2.0, 3.0, 4.0, 6.0, 8.0, 12.0],
    "concs": [2.0, 3.8, 6.5, 7.9, 8.2, 7.0, 5.2, 2.8],
    "kel": 0.18,
    "k12": 0.3,
    "k21": 0.4,
    "fa": [
        0.1375042970,
        0.3072402621,
        0.6406631409,
        0.9154680145,
        1.1084469292,
        1.2833884160,
        1.2935225228,
        1.2247357346,
    ],
}

_WN_IV_DEGENERATE: dict[str, object] = {
    "times": [0.5, 1.0, 2.0, 4.0, 6.0, 8.0, 12.0],
    "concs": [
        9.0483741804,
        8.1873075308,
        6.7032004604,
        4.4932896412,
        3.0119421191,
        2.0189651799,
        0.9071795329,
    ],
    "kel": 0.20,
    "fa": [
        0.9861990212,
        0.9862772159,
        0.9868160420,
        0.9900190074,
        0.9921660193,
        0.9936052044,
        1.0000000000,
    ],
}


class TestWagnerNelsonCrossValidation:
    """Verify openpkflow wagner_nelson() matches R formula implementation.

    R independently implements the same Wagner-Nelson (1963) formula.
    Algebraic identity: values match to floating-point precision.

    Wagner JG, Nelson E (1963). J Pharm Sci, 52(6):610-611.
    DOI: 10.1002/jps.2600520624
    Gibaldi M, Perrier D (1982). Pharmacokinetics, 2nd ed., Chapter 4.
    """

    def test_gibaldi_perrier_fa_matches_r(self) -> None:
        t = _WN_GP_REFERENCE["times"]
        c = _WN_GP_REFERENCE["concs"]
        kel = _WN_GP_REFERENCE["kel"]
        expected_fa = _WN_GP_REFERENCE["fa"]
        result = wagner_nelson(t, c, kel=kel)
        assert np.allclose(result, expected_fa, rtol=1e-8, atol=1e-10), (
            f"WN F_a mismatch:\n  openpkflow={result}\n  R={expected_fa}"
        )

    def test_gibaldi_perrier_fa_monotone_through_absorption_phase(self) -> None:
        t = _WN_GP_REFERENCE["times"]
        c = _WN_GP_REFERENCE["concs"]
        kel = _WN_GP_REFERENCE["kel"]
        fa = wagner_nelson(t, c, kel=kel)
        # F_a should be monotonically non-decreasing for the first 5 time points
        # (absorption phase); slight non-monotonicity in elimination phase is OK
        for i in range(4):
            assert fa[i + 1] >= fa[i] - 0.01, (
                f"F_a non-monotone at i={i}: fa[{i}]={fa[i]:.4f}, fa[{i + 1}]={fa[i + 1]:.4f}"
            )

    def test_gibaldi_perrier_terminal_fa_is_one(self) -> None:
        t = _WN_GP_REFERENCE["times"]
        c = _WN_GP_REFERENCE["concs"]
        kel = _WN_GP_REFERENCE["kel"]
        fa = wagner_nelson(t, c, kel=kel)
        assert fa[-1] == pytest.approx(1.0, abs=0.01), f"Terminal F_a = {fa[-1]:.6f}, expected 1.0"

    def test_gibaldi_perrier_all_fa_non_negative(self) -> None:
        t = _WN_GP_REFERENCE["times"]
        c = _WN_GP_REFERENCE["concs"]
        kel = _WN_GP_REFERENCE["kel"]
        fa = wagner_nelson(t, c, kel=kel)
        assert np.all(fa >= -0.01), f"Negative F_a values: {fa[fa < 0]}"

    def test_iv_bolus_degenerate_fa_near_one(self) -> None:
        """WN deconvolution of a 1-cmt IV bolus profile gives F_a ~ 1 everywhere.

        For a pure IV bolus, absorption is instantaneous at t=0; the
        Wagner-Nelson formula applied to the resulting monoexponential profile
        recovers F_a ~ 1 at every sampling time (beyond t=0).

        Gibaldi M, Perrier D (1982). Pharmacokinetics, 2nd ed., Chapter 4.
        """
        t = _WN_IV_DEGENERATE["times"]
        c = _WN_IV_DEGENERATE["concs"]
        kel = _WN_IV_DEGENERATE["kel"]
        expected = _WN_IV_DEGENERATE["fa"]
        result = wagner_nelson(t, c, kel=kel)
        assert np.allclose(result, expected, rtol=1e-8, atol=1e-10)
        assert np.all(np.abs(result - 1.0) < 0.02), (
            f"IV bolus F_a deviates from 1.0: max_dev={np.max(np.abs(result - 1.0)):.4f}"
        )

    def test_n_timepoints_matches_reference(self) -> None:
        t = _WN_GP_REFERENCE["times"]
        assert len(t) == 8
        assert len(_WN_GP_REFERENCE["fa"]) == 8

    def test_first_fa_near_r_value(self) -> None:
        t = _WN_GP_REFERENCE["times"]
        c = _WN_GP_REFERENCE["concs"]
        kel = _WN_GP_REFERENCE["kel"]
        fa = wagner_nelson(t, c, kel=kel)
        assert fa[0] == pytest.approx(0.1888184098, rel=1e-8)


class TestLooRiegelmanCrossValidation:
    """Verify openpkflow loo_riegelman() matches R formula implementation.

    R independently implements the same Loo-Riegelman (1968) formula.
    Algebraic identity: values match to floating-point precision.

    Loo JCK, Riegelman S (1968). J Pharm Sci, 57(6):918-928.
    DOI: 10.1002/jps.2600570602
    Gibaldi M, Perrier D (1982). Pharmacokinetics, 2nd ed., Chapter 4.
    """

    def test_lr_fa_matches_r(self) -> None:
        t = _LR_REFERENCE["times"]
        c = _LR_REFERENCE["concs"]
        kel = _LR_REFERENCE["kel"]
        k12 = _LR_REFERENCE["k12"]
        k21 = _LR_REFERENCE["k21"]
        expected_fa = _LR_REFERENCE["fa"]
        result = loo_riegelman(t, c, kel=kel, k12=k12, k21=k21)
        assert np.allclose(result, expected_fa, rtol=1e-8, atol=1e-10), (
            f"LR F_a mismatch:\n  openpkflow={result}\n  R={expected_fa}"
        )

    def test_lr_fa_non_negative(self) -> None:
        t = _LR_REFERENCE["times"]
        c = _LR_REFERENCE["concs"]
        fa = loo_riegelman(t, c, kel=0.18, k12=0.3, k21=0.4)
        assert np.all(fa >= -0.01), f"Negative F_a values: {fa[fa < 0]}"

    def test_lr_early_fa_increasing(self) -> None:
        """F_a increases through the absorption phase (first 4 time points)."""
        t = _LR_REFERENCE["times"]
        c = _LR_REFERENCE["concs"]
        fa = loo_riegelman(t, c, kel=0.18, k12=0.3, k21=0.4)
        for i in range(3):
            assert fa[i + 1] > fa[i], (
                f"F_a not increasing at i={i}: fa={fa[i]:.4f} -> {fa[i + 1]:.4f}"
            )

    def test_lr_fa_exceeds_one_in_elimination_phase(self) -> None:
        """LR F_a values > 1.0 in elimination phase are mathematically correct.

        The peripheral compartment term in the LR numerator can exceed the
        denominator (which only accounts for plasma AUC_inf), producing F_a > 1.0.
        This is a known, documented property of the Loo-Riegelman formula and
        not a bug. See Gibaldi & Perrier (1982), Chapter 4.
        """
        t = _LR_REFERENCE["times"]
        c = _LR_REFERENCE["concs"]
        fa = loo_riegelman(t, c, kel=0.18, k12=0.3, k21=0.4)
        assert np.max(fa) > 1.0, "Expected LR F_a to exceed 1.0 in elimination phase"

    def test_lr_first_fa_near_r_value(self) -> None:
        t = _LR_REFERENCE["times"]
        c = _LR_REFERENCE["concs"]
        fa = loo_riegelman(t, c, kel=0.18, k12=0.3, k21=0.4)
        assert fa[0] == pytest.approx(0.1375042970, rel=1e-8)

    def test_lr_n_timepoints_matches_reference(self) -> None:
        assert len(_LR_REFERENCE["times"]) == 8
        assert len(_LR_REFERENCE["fa"]) == 8
