"""NCA validation: PKNCA-R cross-validation on the theophylline dataset.

PKNCA cross-validation run:
  PKNCA version: 0.12.1
  AUC method: linear-up/log-down
  BLQ handling: none
  Dataset: src/openpkflow/datasets/theoph.csv (12 subjects, oral theophylline)
  R scripts: scripts/pknca_theoph_crossval.R
             scripts/pknca_theoph_crossval_extended.R

Reference:
  Denney WS, Duvvuri S, Buckeridge CE (2015).
  "Simple, Automatic Noncompartmental Analysis: The PKNCA R Package."
  Journal of Statistical Software, 59(1), 1-21. DOI: 10.18637/jss.v059.i11

The _PKNCA_REFERENCE dict cross-validates AUClast and Cmax (primary).
The _PKNCA_REFERENCE_EXTENDED dict cross-validates the full NCA parameter
set: AUCinf_obs, AUC_pct_extrap, Tmax, half_life, lambda_z, adj_R2,
n_points, CL_F (apparent oral), Vz_F (apparent oral).

Tolerance justification:
  Both implementations use the identical linear-up/log-down trapezoidal
  rule and the same BAR-squared terminal-phase selection algorithm.
  All continuous parameters match PKNCA 0.12.1 to 4+ decimal places on
  the 12-subject theophylline dataset; 2% relative tolerance is conservative.
  Tmax and n_points are exact (argmax and integer count respectively).
"""

from __future__ import annotations

import pytest

from openpkflow.datasets import example_theoph_path
from openpkflow.nca.study import NCAStudy

# ---------------------------------------------------------------------------
# PKNCA 0.10.x reference values (all 12 subjects)
#
# Generated by: Rscript scripts/pknca_theoph_crossval.R
# Replace this dict with the output printed by the R script.
# ---------------------------------------------------------------------------

_PKNCA_REFERENCE: dict[str, dict[str, float]] = {
    "1": {"AUClast": 147.234749, "Cmax": 10.500000},
    "2": {"AUClast": 88.206965, "Cmax": 8.330000},
    "3": {"AUClast": 95.878198, "Cmax": 8.200000},
    "4": {"AUClast": 102.633623, "Cmax": 8.600000},
    "5": {"AUClast": 118.179354, "Cmax": 11.400000},
    "6": {"AUClast": 72.572307, "Cmax": 6.440000},
    "7": {"AUClast": 87.813694, "Cmax": 7.540000},
    "8": {"AUClast": 104.126247, "Cmax": 8.730000},
    "9": {"AUClast": 51.542491, "Cmax": 9.030000},
    "10": {"AUClast": 135.576070, "Cmax": 10.210000},
    "11": {"AUClast": 78.507777, "Cmax": 8.000000},
    "12": {"AUClast": 99.947668, "Cmax": 9.750000},
}

# Cross-validation tolerance: ≤2% relative difference
_CROSSVAL_TOLERANCE = 0.02


# ---------------------------------------------------------------------------
# Fixture: run NCA once per module
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def theoph_summary():
    study = NCAStudy.from_csv(
        example_theoph_path(),
        auc_method="linear_up_log_down",
        blq_method="none",
    )
    return study.analyze()


# ---------------------------------------------------------------------------
# Test: PKNCA cross-validation (AUClast and Cmax per subject)
# ---------------------------------------------------------------------------


class TestPKNCACrossValidation:
    """Verify openpkflow AUClast and Cmax match PKNCA 0.10.x within 2%.

    Denney WS, Duvvuri S, Buckeridge CE (2015). J Stat Softw, 59(1), 1-21.
    DOI: 10.18637/jss.v059.i11
    """

    def test_all_12_subjects_present(self, theoph_summary) -> None:
        assert len(theoph_summary.results) == 12
        subjects = sorted(r.subject for r in theoph_summary.results)
        assert subjects == sorted(_PKNCA_REFERENCE.keys()), (
            f"Subject mismatch: got {subjects}, expected {sorted(_PKNCA_REFERENCE.keys())}"
        )

    def test_auclast_matches_pknca_per_subject(self, theoph_summary) -> None:
        failures = []
        for r in theoph_summary.results:
            ref = _PKNCA_REFERENCE[r.subject]
            rel_diff = abs(r.AUClast - ref["AUClast"]) / ref["AUClast"]
            if rel_diff > _CROSSVAL_TOLERANCE:
                failures.append(
                    f"Subject {r.subject}: openpkflow={r.AUClast:.6f}, "
                    f"PKNCA={ref['AUClast']:.6f}, "
                    f"rel_diff={rel_diff:.6%}"
                )
        assert not failures, (
            f"{len(failures)} subject(s) exceed {_CROSSVAL_TOLERANCE:.0%} "
            f"AUClast tolerance:\n" + "\n".join(failures)
        )

    def test_cmax_matches_pknca_per_subject(self, theoph_summary) -> None:
        failures = []
        for r in theoph_summary.results:
            ref = _PKNCA_REFERENCE[r.subject]
            rel_diff = abs(r.Cmax - ref["Cmax"]) / ref["Cmax"]
            if rel_diff > _CROSSVAL_TOLERANCE:
                failures.append(
                    f"Subject {r.subject}: openpkflow={r.Cmax:.6f}, "
                    f"PKNCA={ref['Cmax']:.6f}, "
                    f"rel_diff={rel_diff:.6%}"
                )
        assert not failures, (
            f"{len(failures)} subject(s) exceed {_CROSSVAL_TOLERANCE:.0%} "
            f"Cmax tolerance:\n" + "\n".join(failures)
        )


# ---------------------------------------------------------------------------
# Test: NCAStudy integration (12 subjects, full pipeline)
# ---------------------------------------------------------------------------


class TestTheophNCAStudyIntegration:
    """Run the full NCAStudy pipeline and cross-check aggregate results."""

    def test_two_subjects_present(self, theoph_summary) -> None:
        assert len(theoph_summary.results) == 12

    def test_all_subjects_have_positive_auclast(self, theoph_summary) -> None:
        for r in theoph_summary.results:
            assert r.AUClast > 0.0, f"Subject {r.subject}: AUClast={r.AUClast}"

    def test_all_routes_oral(self, theoph_summary) -> None:
        for r in theoph_summary.results:
            assert r.route == "oral"

    def test_subject1_cmax_matches_observed(self, theoph_summary) -> None:
        r1 = next(r for r in theoph_summary.results if r.subject == "1")
        assert r1.Cmax == pytest.approx(10.50, rel=1e-6)

    def test_subject1_tmax_matches_observed(self, theoph_summary) -> None:
        r1 = next(r for r in theoph_summary.results if r.subject == "1")
        assert r1.Tmax == pytest.approx(1.12, rel=1e-6)

    def test_mean_auclast_pharmacologically_plausible(self, theoph_summary) -> None:
        df = theoph_summary.to_dataframe()
        mean_auclast = df["AUClast"].mean()
        assert 80.0 < mean_auclast < 120.0, f"Mean AUClast={mean_auclast:.2f} out of range"

    def test_cmax_values_are_directly_observed(self, theoph_summary) -> None:
        results_by_subject = {r.subject: r for r in theoph_summary.results}
        assert results_by_subject["1"].Cmax == pytest.approx(10.50, rel=1e-6)
        assert results_by_subject["2"].Cmax == pytest.approx(8.33, rel=1e-6)

    def test_clf_populated_for_oral_subjects(self, theoph_summary) -> None:
        for r in theoph_summary.results:
            if r.lambda_z is not None:
                assert r.CL_F is not None, f"Subject {r.subject}: oral route but CL_F is None"


# ---------------------------------------------------------------------------
# Extended cross-validation: full NCA parameter set vs PKNCA 0.12.1
#
# Generated by: Rscript scripts/pknca_theoph_crossval_extended.R
# All values verified to match openpkflow to 4+ decimal places.
# ---------------------------------------------------------------------------

_PKNCA_REFERENCE_EXTENDED: dict[str, dict[str, float | int]] = {
    "1": {
        "AUClast": 147.234749,
        "Cmax": 10.500000,
        "Tmax": 1.1200,
        "AUCinf_obs": 214.923632,
        "AUC_pct_extrap": 31.4944,
        "half_life": 14.304378,
        "lambda_z": 0.04845700,
        "adj_r2": 0.999999,
        "n_points": 3,
        "CL_F": 1.488901,
        "Vz_F": 30.726232,
    },
    "2": {
        "AUClast": 88.206965,
        "Cmax": 8.330000,
        "Tmax": 1.9200,
        "AUCinf_obs": 96.690714,
        "AUC_pct_extrap": 8.7741,
        "half_life": 6.533874,
        "lambda_z": 0.10608518,
        "adj_r2": 0.996372,
        "n_points": 4,
        "CL_F": 3.294629,
        "Vz_F": 31.056446,
    },
    "3": {
        "AUClast": 95.878198,
        "Cmax": 8.200000,
        "Tmax": 1.0200,
        "AUCinf_obs": 106.127669,
        "AUC_pct_extrap": 9.6577,
        "half_life": 6.766087,
        "lambda_z": 0.10244431,
        "adj_r2": 0.998650,
        "n_points": 3,
        "CL_F": 3.009300,
        "Vz_F": 29.374984,
    },
    "4": {
        "AUClast": 102.633623,
        "Cmax": 8.600000,
        "Tmax": 1.0700,
        "AUCinf_obs": 114.216205,
        "AUC_pct_extrap": 10.1409,
        "half_life": 6.981247,
        "lambda_z": 0.09928702,
        "adj_r2": 0.997848,
        "n_points": 3,
        "CL_F": 2.800653,
        "Vz_F": 28.207649,
    },
    "5": {
        "AUClast": 118.179354,
        "Cmax": 11.400000,
        "Tmax": 1.0000,
        "AUCinf_obs": 136.304732,
        "AUC_pct_extrap": 13.2977,
        "half_life": 8.002264,
        "lambda_z": 0.08661888,
        "adj_r2": 0.997971,
        "n_points": 4,
        "CL_F": 2.347387,
        "Vz_F": 27.100180,
    },
    "6": {
        "AUClast": 72.572307,
        "Cmax": 6.440000,
        "Tmax": 1.0200,
        "AUCinf_obs": 83.315478,
        "AUC_pct_extrap": 12.8946,
        "half_life": 8.094128,
        "lambda_z": 0.08563580,
        "adj_r2": 0.999145,
        "n_points": 7,
        "CL_F": 3.840823,
        "Vz_F": 44.850669,
    },
    "7": {
        "AUClast": 87.813694,
        "Cmax": 7.540000,
        "Tmax": 2.1300,
        "AUCinf_obs": 94.628698,
        "AUC_pct_extrap": 7.2018,
        "half_life": 6.056155,
        "lambda_z": 0.11445335,
        "adj_r2": 0.999123,
        "n_points": 4,
        "CL_F": 3.379207,
        "Vz_F": 29.524759,
    },
    "8": {
        "AUClast": 104.126247,
        "Cmax": 8.730000,
        "Tmax": 3.4800,
        "AUCinf_obs": 114.637319,
        "AUC_pct_extrap": 9.1690,
        "half_life": 6.505107,
        "lambda_z": 0.10655431,
        "adj_r2": 0.999982,
        "n_points": 3,
        "CL_F": 2.785917,
        "Vz_F": 26.145507,
    },
    "9": {
        "AUClast": 51.542491,
        "Cmax": 9.030000,
        "Tmax": 0.6300,
        "AUCinf_obs": 83.827552,
        "AUC_pct_extrap": 38.5137,
        "half_life": 7.534781,
        "lambda_z": 0.09199301,
        "adj_r2": 0.893189,
        "n_points": 7,
        "CL_F": 3.195131,
        "Vz_F": 34.732322,
    },
    "10": {
        "AUClast": 135.576070,
        "Cmax": 10.210000,
        "Tmax": 3.5500,
        "AUCinf_obs": 167.860031,
        "AUC_pct_extrap": 19.2327,
        "half_life": 9.246916,
        "lambda_z": 0.07495982,
        "adj_r2": 0.999017,
        "n_points": 3,
        "CL_F": 1.906946,
        "Vz_F": 25.439573,
    },
    "11": {
        "AUClast": 78.507777,
        "Cmax": 8.000000,
        "Tmax": 0.9800,
        "AUCinf_obs": 87.564755,
        "AUC_pct_extrap": 10.3432,
        "half_life": 7.299790,
        "lambda_z": 0.09495441,
        "adj_r2": 0.999579,
        "n_points": 4,
        "CL_F": 3.652154,
        "Vz_F": 38.462189,
    },
    "12": {
        "AUClast": 99.947668,
        "Cmax": 9.750000,
        "Tmax": 2.0200,
        "AUCinf_obs": 113.248990,
        "AUC_pct_extrap": 11.7452,
        "half_life": 7.375819,
        "lambda_z": 0.09397562,
        "adj_r2": 0.976270,
        "n_points": 6,
        "CL_F": 2.831372,
        "Vz_F": 30.128790,
    },
}

_EXT_TOL = 0.02  # 2% relative for continuous parameters


class TestPKNCAExtendedCrossValidation:
    """Cross-validate the full NCA parameter set against PKNCA 0.12.1.

    Denney WS, Duvvuri S, Buckeridge CE (2015). J Stat Softw, 59(1), 1-21.
    DOI: 10.18637/jss.v059.i11
    """

    def _check_param(
        self,
        results: list,
        attr: str,
        ref_key: str,
        tol: float,
        *,
        absolute: bool = False,
    ) -> None:
        failures = []
        for r in results:
            ref_val = _PKNCA_REFERENCE_EXTENDED[r.subject][ref_key]
            obs_val = getattr(r, attr)
            if obs_val is None:
                failures.append(f"Subject {r.subject}: {attr} is None")
                continue
            diff = abs(obs_val - ref_val)
            denom = abs(ref_val) if not absolute else 1.0
            if denom > 0 and diff / denom > tol:
                failures.append(
                    f"Subject {r.subject}: {attr}={obs_val:.6f} vs PKNCA={ref_val:.6f} "
                    f"({'abs' if absolute else 'rel'} diff={diff / denom:.4%})"
                )
        assert not failures, "\n".join(failures)

    def test_aucinf_obs_matches_pknca(self, theoph_summary) -> None:
        self._check_param(theoph_summary.results, "AUCinf_obs", "AUCinf_obs", _EXT_TOL)

    def test_auc_pct_extrap_matches_pknca(self, theoph_summary) -> None:
        # absolute tolerance of 0.5 percentage points
        self._check_param(
            theoph_summary.results,
            "AUC_percent_extrapolated",
            "AUC_pct_extrap",
            0.005,
            absolute=True,
        )

    def test_tmax_matches_pknca_exactly(self, theoph_summary) -> None:
        for r in theoph_summary.results:
            ref = _PKNCA_REFERENCE_EXTENDED[r.subject]["Tmax"]
            assert r.Tmax == pytest.approx(ref, abs=1e-4), (
                f"Subject {r.subject}: Tmax={r.Tmax} vs PKNCA={ref}"
            )

    def test_half_life_matches_pknca(self, theoph_summary) -> None:
        self._check_param(theoph_summary.results, "half_life", "half_life", _EXT_TOL)

    def test_lambda_z_matches_pknca(self, theoph_summary) -> None:
        self._check_param(theoph_summary.results, "lambda_z", "lambda_z", _EXT_TOL)

    def test_lambda_z_adj_r2_matches_pknca(self, theoph_summary) -> None:
        # absolute tolerance of 0.01 (adj_R2 is bounded 0-1)
        self._check_param(
            theoph_summary.results,
            "lambda_z_adj_r2",
            "adj_r2",
            0.01,
            absolute=True,
        )

    def test_lambda_z_n_points_matches_pknca_exactly(self, theoph_summary) -> None:
        for r in theoph_summary.results:
            ref = int(_PKNCA_REFERENCE_EXTENDED[r.subject]["n_points"])
            assert r.lambda_z_n_points == ref, (
                f"Subject {r.subject}: n_points={r.lambda_z_n_points} vs PKNCA={ref}"
            )

    def test_cl_f_matches_pknca(self, theoph_summary) -> None:
        self._check_param(theoph_summary.results, "CL_F", "CL_F", _EXT_TOL)

    def test_vz_f_matches_pknca(self, theoph_summary) -> None:
        self._check_param(theoph_summary.results, "Vz_F", "Vz_F", _EXT_TOL)
