"""Urinary NCA cross-validation: independent R implementation.

Independent R formula implementation cross-validation run:
  R script: scripts/urine_nca_crossval.R
  Strategy: algebraic identity (no external R packages).
  Both R and openpkflow implement the same formulas directly.
  Values should match to floating-point precision (< 1e-10 relative difference).

Dataset: 3 synthetic subjects derived from 1-compartment IV bolus renal
excretion model with known analytical true values.

Model: C(t) = (D/V)*exp(-CL/V * t)
       Renal excretion rate: dAe/dt = CLr * C(t)
       Ae(t1,t2) = CLr * (D/CL) * (exp(-k*t1) - exp(-k*t2))
       AUCinf = D / CL  (exact, from Gibaldi & Perrier Eq. 1-4)
       CLr_true = CLr  (exact when AUCinf is used to infinity)

Formulas (both R and openpkflow):
  Ae_i = volume_i * conc_i  (amount per collection interval)
  Ae_cumulative = cumulative sum of Ae_i
  CLr = Ae_total / AUCinf
  %Ae = Ae_total / dose * 100

Note on truncation: Urine collection ends at 24h (not infinity). The computed
CLr and %Ae will be slightly below the true analytical values due to this
truncation. The deviation is within ~1% of the true value for all subjects
(verified analytically in the R script).

References:
  Rowland M, Tozer TN (2011). Clinical Pharmacokinetics 4th ed., Ch. 9.
    Defines CLr = Ae_total / AUCinf and %Ae = Ae_total / dose * 100.
  Gibaldi M, Perrier D (1982). Pharmacokinetics, 2nd ed.
    Eq. 1-4: AUCinf = D/CL for 1-cmt IV bolus.
"""

from __future__ import annotations

import numpy as np
import pytest

from openpkflow.nca.methods import (
    cumulative_urinary_excretion,
    percent_excreted,
    renal_clearance,
)

# ---------------------------------------------------------------------------
# R cross-validation reference values
#
# Generated by: Rscript scripts/urine_nca_crossval.R
# Formula: Ae_i = volume_i * conc_i; CLr = Ae_total / AUCinf
# ---------------------------------------------------------------------------

_URINE_REFERENCE: dict[str, dict[str, object]] = {
    "1": {
        "volumes": [0.4000, 0.4000, 0.4000, 1.2000],
        "concs": [55.067104, 24.743245, 11.117856, 2.749607],
        "auc_inf": 50.000000,
        "dose": 100.0,
        "ae_cumulative": [22.026841, 31.924139, 36.371282, 39.670810],
        "ae_total": 39.670810,
        "CLr": 0.793416,
        "pct_ae": 39.670810,
        "true_CLr": 0.8000,
        "true_fe_pct": 40.0000,
    },
    "2": {
        "volumes": [0.4000, 0.4000, 0.4000, 1.2000],
        "concs": [94.818084, 34.881624, 12.832232, 2.365416],
        "auc_inf": 40.000000,
        "dose": 200.0,
        "ae_cumulative": [37.927234, 51.879883, 57.012776, 59.851275],
        "ae_total": 59.851275,
        "CLr": 1.496282,
        "pct_ae": 29.925637,
        "true_CLr": 1.5000,
        "true_fe_pct": 30.0000,
    },
    "3": {
        "volumes": [0.4000, 0.4000, 0.4000, 1.2000],
        "concs": [123.900983, 55.672300, 25.015177, 6.186615],
        "auc_inf": 50.000000,
        "dose": 150.0,
        "ae_cumulative": [49.560393, 71.829313, 81.835384, 89.259323],
        "ae_total": 89.259323,
        "CLr": 1.785186,
        "pct_ae": 59.506215,
        "true_CLr": 1.8000,
        "true_fe_pct": 60.0000,
    },
}

_TOL_MATCH = 1e-5  # tolerance for R algebraic match
_TOL_TRUE = 0.02  # tolerance vs analytical true value (24h truncation)


class TestUrinaryNCACrossValidation:
    """Verify urinary NCA functions match independent R formula implementation.

    R independently implements the same formulas (cumulative Ae, CLr, %Ae).
    Algebraic identity: values should match to floating-point precision.
    Analytical deviation (truncation at 24h): <1% for all subjects.

    Rowland M, Tozer TN (2011). Clinical Pharmacokinetics 4th ed., Ch. 9.
    """

    def _ref(self, subj: str) -> dict:
        return _URINE_REFERENCE[subj]

    def test_all_3_subjects_present(self) -> None:
        assert set(_URINE_REFERENCE.keys()) == {"1", "2", "3"}

    # --- Cumulative Ae matches R ---

    def test_cumulative_ae_matches_r_subject1(self) -> None:
        r = self._ref("1")
        # Times are just labels; Ae_i = vol_i * conc_i
        times = [2.0, 6.0, 10.0, 18.0]  # midpoints of [0-4],[4-8],[8-12],[12-24]
        result = cumulative_urinary_excretion(times, r["volumes"], r["concs"])
        expected = r["ae_cumulative"]
        assert np.allclose(result, expected, rtol=_TOL_MATCH, atol=1e-8), (
            f"Cumulative Ae mismatch S1:\n  openpkflow={result}\n  R={expected}"
        )

    def test_cumulative_ae_matches_r_subject2(self) -> None:
        r = self._ref("2")
        times = [2.0, 6.0, 10.0, 18.0]
        result = cumulative_urinary_excretion(times, r["volumes"], r["concs"])
        assert np.allclose(result, r["ae_cumulative"], rtol=_TOL_MATCH, atol=1e-8)

    def test_cumulative_ae_matches_r_subject3(self) -> None:
        r = self._ref("3")
        times = [2.0, 6.0, 10.0, 18.0]
        result = cumulative_urinary_excretion(times, r["volumes"], r["concs"])
        assert np.allclose(result, r["ae_cumulative"], rtol=_TOL_MATCH, atol=1e-8)

    # --- CLr matches R ---

    def test_clr_matches_r_subject1(self) -> None:
        r = self._ref("1")
        result = renal_clearance(r["ae_total"], r["auc_inf"])
        assert result == pytest.approx(r["CLr"], rel=_TOL_MATCH)

    def test_clr_matches_r_subject2(self) -> None:
        r = self._ref("2")
        result = renal_clearance(r["ae_total"], r["auc_inf"])
        assert result == pytest.approx(r["CLr"], rel=_TOL_MATCH)

    def test_clr_matches_r_subject3(self) -> None:
        r = self._ref("3")
        result = renal_clearance(r["ae_total"], r["auc_inf"])
        assert result == pytest.approx(r["CLr"], rel=_TOL_MATCH)

    # --- %Ae matches R ---

    def test_pct_ae_matches_r_subject1(self) -> None:
        r = self._ref("1")
        result = percent_excreted(r["ae_total"], r["dose"])
        assert result == pytest.approx(r["pct_ae"], rel=_TOL_MATCH)

    def test_pct_ae_matches_r_subject2(self) -> None:
        r = self._ref("2")
        result = percent_excreted(r["ae_total"], r["dose"])
        assert result == pytest.approx(r["pct_ae"], rel=_TOL_MATCH)

    def test_pct_ae_matches_r_subject3(self) -> None:
        r = self._ref("3")
        result = percent_excreted(r["ae_total"], r["dose"])
        assert result == pytest.approx(r["pct_ae"], rel=_TOL_MATCH)

    # --- Analytical ground truth (within 24h truncation error) ---

    def test_clr_within_1pct_of_true_analytical_value(self) -> None:
        """Computed CLr is within 1% of the true analytical CLr for all subjects.

        Truncation at 24h accounts for the ~1% gap between computed and true CLr.
        This confirms the formula is correct (not just algebraically matching R).

        Rowland M, Tozer TN (2011). Clinical Pharmacokinetics 4th ed., Ch. 9.
        """
        failures = []
        for subj, r in _URINE_REFERENCE.items():
            clr_calc = renal_clearance(r["ae_total"], r["auc_inf"])
            true_clr = r["true_CLr"]
            rel_err = abs(clr_calc - true_clr) / true_clr
            if rel_err > _TOL_TRUE:
                failures.append(
                    f"Subject {subj}: CLr={clr_calc:.4f} vs true={true_clr:.4f} "
                    f"(rel_err={rel_err:.4%})"
                )
        assert not failures, "\n".join(failures)

    def test_pct_ae_within_1pct_of_true_analytical_value(self) -> None:
        """Computed %Ae is within 1% of the true analytical %Ae for all subjects.

        Rowland M, Tozer TN (2011). Clinical Pharmacokinetics 4th ed., Ch. 9.
        """
        failures = []
        for subj, r in _URINE_REFERENCE.items():
            pct_calc = percent_excreted(r["ae_total"], r["dose"])
            true_pct = r["true_fe_pct"]
            rel_err = abs(pct_calc - true_pct) / true_pct
            if rel_err > _TOL_TRUE:
                failures.append(
                    f"Subject {subj}: %Ae={pct_calc:.4f} vs true={true_pct:.4f} "
                    f"(rel_err={rel_err:.4%})"
                )
        assert not failures, "\n".join(failures)

    # --- Internal consistency checks ---

    def test_ae_cumulative_is_non_decreasing(self) -> None:
        for subj, r in _URINE_REFERENCE.items():
            times = [2.0, 6.0, 10.0, 18.0]
            ae = cumulative_urinary_excretion(times, r["volumes"], r["concs"])
            for i in range(len(ae) - 1):
                assert ae[i + 1] >= ae[i], f"Subject {subj}: Ae not monotone at interval {i}: {ae}"

    def test_ae_total_equals_last_cumulative_value(self) -> None:
        for subj, r in _URINE_REFERENCE.items():
            times = [2.0, 6.0, 10.0, 18.0]
            ae_cum = cumulative_urinary_excretion(times, r["volumes"], r["concs"])
            assert ae_cum[-1] == pytest.approx(r["ae_total"], rel=_TOL_MATCH), (
                f"Subject {subj}: ae_cum[-1]={ae_cum[-1]:.6f} vs ae_total={r['ae_total']:.6f}"
            )

    def test_clr_formula_identity(self) -> None:
        """CLr = Ae_total / AUCinf is verified as an identity for all subjects."""
        for subj, r in _URINE_REFERENCE.items():
            expected = r["ae_total"] / r["auc_inf"]
            result = renal_clearance(r["ae_total"], r["auc_inf"])
            assert result == pytest.approx(expected, rel=1e-12), (
                f"Subject {subj}: CLr={result} vs manual={expected}"
            )

    def test_pct_ae_formula_identity(self) -> None:
        """pct_ae = Ae_total / dose * 100 is verified as an identity."""
        for subj, r in _URINE_REFERENCE.items():
            expected = r["ae_total"] / r["dose"] * 100.0
            result = percent_excreted(r["ae_total"], r["dose"])
            assert result == pytest.approx(expected, rel=1e-12), (
                f"Subject {subj}: pct_ae={result} vs manual={expected}"
            )

    def test_higher_clr_gives_higher_pct_ae(self) -> None:
        """Subject 3 has highest CLr/CL ratio (0.60) so highest %Ae."""
        pct1 = percent_excreted(_URINE_REFERENCE["1"]["ae_total"], _URINE_REFERENCE["1"]["dose"])
        pct3 = percent_excreted(_URINE_REFERENCE["3"]["ae_total"], _URINE_REFERENCE["3"]["dose"])
        assert pct3 > pct1, (
            f"Subject 3 (fe=0.60) should have higher %Ae than Subject 1 (fe=0.40); "
            f"got pct3={pct3:.2f}, pct1={pct1:.2f}"
        )
