"""ML / surrogate modeling -- experimental.

Requires PyTorch (installed via ``pip install openpkflow[ml]``).

Features
--------
PKSurrogate
    MLP surrogate that approximates 1-compartment oral PK profiles.
    Trained from synthetic data generated by the openpkflow sim engine.
    Marked EXPERIMENTAL -- not validated for regulatory use.
"""

from __future__ import annotations

from .surrogate import PKSurrogate

__all__ = ["PKSurrogate"]
