"""Experimental: torch MLP surrogate for PK concentration-time profiles.

This module is clearly marked EXPERIMENTAL. It learns to approximate the
analytical 1-compartment oral profile from (time, dose, CL_F, Vz_F, ka)
feature vectors using a shallow multi-layer perceptron.

It is NOT a replacement for analytical PK simulation or validated NLME
software. Use it for rapid screening, sensitivity analysis, or uncertainty
propagation where approximate predictions are acceptable.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

import numpy as np


def _require_torch() -> Any:
    try:
        import torch  # type: ignore[import]

        return torch
    except ImportError as exc:
        raise ImportError(
            "ML surrogate requires PyTorch. Install with: pip install openpkflow[ml]"
        ) from exc


@dataclass
class PKSurrogate:
    """Experimental MLP surrogate for 1-compartment oral PK profiles.

    Learns the mapping (time, dose, CL_F, Vz_F, ka) -> concentration from
    synthetic training data generated by the openpkflow sim engine.

    Parameters
    ----------
    hidden_sizes : tuple[int, ...]
        Sizes of hidden layers. Default (64, 64).
    epochs : int
        Training epochs. Default 300.
    lr : float
        Adam learning rate. Default 1e-3.
    seed : int or None, optional
        Random seed for reproducible training. Default None.

    Attributes
    ----------
    train_loss_history : list[float]
        MSE loss recorded at each epoch.
    """

    hidden_sizes: tuple[int, ...] = (64, 64)
    epochs: int = 300
    lr: float = 1e-3
    seed: int | None = None

    train_loss_history: list[float] = field(default_factory=list, repr=False)

    # private: set by fit()
    _model: Any = field(default=None, init=False, repr=False)
    _x_mean: np.ndarray = field(default=None, init=False, repr=False)  # type: ignore[assignment]
    _x_std: np.ndarray = field(default=None, init=False, repr=False)  # type: ignore[assignment]
    _y_mean: float = field(default=0.0, init=False, repr=False)
    _y_std: float = field(default=1.0, init=False, repr=False)

    def _build_net(self, n_features: int) -> Any:
        torch = _require_torch()

        layers: list[Any] = [torch.nn.Linear(n_features, self.hidden_sizes[0]), torch.nn.Tanh()]
        for i in range(1, len(self.hidden_sizes)):
            layers += [
                torch.nn.Linear(self.hidden_sizes[i - 1], self.hidden_sizes[i]),
                torch.nn.Tanh(),
            ]
        layers.append(torch.nn.Linear(self.hidden_sizes[-1], 1))
        return torch.nn.Sequential(*layers)

    def fit(self, X: np.ndarray, y: np.ndarray) -> PKSurrogate:
        """Train the MLP surrogate on feature matrix X and target vector y.

        Parameters
        ----------
        X : np.ndarray
            Feature matrix, shape (n_samples, n_features).
            Expected features in order: [time, dose, CL_F, Vz_F, ka].
        y : np.ndarray
            Target concentrations, shape (n_samples,). Must be >= 0.

        Returns
        -------
        PKSurrogate
            Self, for chaining.
        """
        torch = _require_torch()

        if self.seed is not None:
            torch.manual_seed(self.seed)
            np.random.seed(self.seed)

        X = np.asarray(X, dtype=np.float32)
        y = np.asarray(y, dtype=np.float32)

        # z-score normalisation
        self._x_mean = X.mean(axis=0)
        self._x_std = np.where(X.std(axis=0) > 0, X.std(axis=0), 1.0)
        self._y_mean = float(y.mean())
        self._y_std = float(y.std()) if y.std() > 0 else 1.0

        X_norm = (X - self._x_mean) / self._x_std
        y_norm = (y - self._y_mean) / self._y_std

        X_t = torch.tensor(X_norm, dtype=torch.float32)
        y_t = torch.tensor(y_norm, dtype=torch.float32).unsqueeze(1)

        self._model = self._build_net(X.shape[1])
        optimizer = torch.optim.Adam(self._model.parameters(), lr=self.lr)
        criterion = torch.nn.MSELoss()

        self.train_loss_history.clear()
        self._model.train()
        for _ in range(self.epochs):
            optimizer.zero_grad()
            pred = self._model(X_t)
            loss = criterion(pred, y_t)
            loss.backward()
            optimizer.step()
            self.train_loss_history.append(float(loss.item()))

        self._model.eval()
        return self

    def predict(self, X: np.ndarray) -> np.ndarray:
        """Predict concentrations for the given feature matrix.

        Parameters
        ----------
        X : np.ndarray
            Feature matrix, shape (n_samples, n_features). Must use the same
            feature order as the training data passed to ``fit()``.

        Returns
        -------
        np.ndarray
            Predicted concentrations, shape (n_samples,). Values clipped to >= 0.

        Raises
        ------
        RuntimeError
            If called before ``fit()``.
        """
        if self._model is None:
            raise RuntimeError("Call fit() before predict().")

        torch = _require_torch()

        X = np.asarray(X, dtype=np.float32)
        X_norm = (X - self._x_mean) / self._x_std
        X_t = torch.tensor(X_norm, dtype=torch.float32)

        with torch.no_grad():
            pred_norm = self._model(X_t).squeeze(1).numpy()

        return np.maximum(pred_norm * self._y_std + self._y_mean, 0.0)

    @classmethod
    def from_1cmt_oral(
        cls,
        *,
        n_samples: int = 2000,
        n_timepoints: int = 20,
        t_max: float = 24.0,
        param_ranges: dict[str, tuple[float, float]] | None = None,
        hidden_sizes: tuple[int, ...] = (64, 64),
        epochs: int = 300,
        lr: float = 1e-3,
        seed: int | None = None,
    ) -> PKSurrogate:
        """Train a surrogate from synthetic 1-compartment oral simulation data.

        Generates ``n_samples`` parameter sets sampled uniformly from
        ``param_ranges``, simulates the 1-cmt oral profile at ``n_timepoints``
        time points, and trains the MLP on the resulting dataset.

        Parameters
        ----------
        n_samples : int, optional
            Number of parameter combinations to simulate. Default 2000.
        n_timepoints : int, optional
            Number of time points per profile. Default 20.
        t_max : float, optional
            Maximum simulation time (same units as rate constants). Default 24.0.
        param_ranges : dict or None, optional
            Dict mapping parameter name to (min, max) range. Keys must be
            ``dose``, ``CL_F``, ``Vz_F``, ``ka``. If None, uses typical oral
            small-molecule defaults:
            dose=[10, 500], CL_F=[1, 30], Vz_F=[10, 200], ka=[0.1, 3.0].
        hidden_sizes : tuple[int, ...], optional
            MLP hidden layer sizes. Default (64, 64).
        epochs : int, optional
            Training epochs. Default 300.
        lr : float, optional
            Adam learning rate. Default 1e-3.
        seed : int or None, optional
            Random seed for reproducibility.

        Returns
        -------
        PKSurrogate
            Trained surrogate.

        Notes
        -----
        Uses the openpkflow analytical 1-cmt oral formula directly (no ODE
        solver). Training data is entirely synthetic -- model accuracy depends
        on how well param_ranges covers the target parameter space.
        """
        from openpkflow.sim.methods import c_1cmt_oral

        defaults = {
            "dose": (10.0, 500.0),
            "CL_F": (1.0, 30.0),
            "Vz_F": (10.0, 200.0),
            "ka": (0.1, 3.0),
        }
        ranges = {**defaults, **(param_ranges or {})}

        rng = np.random.default_rng(seed)
        times = np.linspace(0.1, t_max, n_timepoints)

        X_rows: list[list[float]] = []
        y_rows: list[float] = []

        for _ in range(n_samples):
            dose = rng.uniform(*ranges["dose"])
            cl_f = rng.uniform(*ranges["CL_F"])
            vz_f = rng.uniform(*ranges["Vz_F"])
            ka = rng.uniform(*ranges["ka"])

            concs = c_1cmt_oral(times, dose=dose, CL_F=cl_f, Vz_F=vz_f, ka=ka)

            for t, c in zip(times, concs, strict=True):
                X_rows.append([t, dose, cl_f, vz_f, ka])
                y_rows.append(float(c))

        X = np.array(X_rows, dtype=np.float32)
        y = np.array(y_rows, dtype=np.float32)

        surrogate = cls(hidden_sizes=hidden_sizes, epochs=epochs, lr=lr, seed=seed)
        surrogate.fit(X, y)
        return surrogate

    def summary(self) -> str:
        """Return an ASCII summary of the surrogate and training status.

        Returns
        -------
        str
            Multi-line summary.
        """
        n_params = (
            sum(p.numel() for p in self._model.parameters()) if self._model is not None else 0
        )
        lines = [
            "PKSurrogate (EXPERIMENTAL)",
            "==========================",
            f"Architecture : {self.hidden_sizes}",
            f"Epochs       : {self.epochs}",
            f"LR           : {self.lr}",
            f"Parameters   : {n_params}",
        ]
        if self.train_loss_history:
            lines.append(f"Initial loss : {self.train_loss_history[0]:.4f}")
            lines.append(f"Final loss   : {self.train_loss_history[-1]:.4f}")
        else:
            lines.append("Status       : not trained")
        lines.append("")
        lines.append(
            "DISCLAIMER: This is an experimental ML surrogate -- not a validated "
            "pharmacokinetic tool. Do not use for regulatory submissions."
        )
        return "\n".join(lines)
