.libPaths('D:/R-library/4.6')
library(bootf2)
data(shah1998)
cat("Class:", class(shah1998), "\n")
cat("Names:", paste(names(shah1998), collapse=", "), "\n")
cat("tp:", paste(shah1998$tp, collapse=", "), "\n")
cat("ref dim:", nrow(shah1998$ref), "x", ncol(shah1998$ref), "\n")
cat("ref:\n")
print(shah1998$ref)
